package securebackup

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"strings"
)

const (
	backupMagic       = "OMBAKUP1"
	headerSize        = len(backupMagic) + 4 + 8
	defaultChunkSize  = 1 << 20
	minimumChunkSize  = 4 << 10
	maximumChunkSize  = 8 << 20
	encryptionKeySize = 32
)

var (
	ErrInvalidEncryptedBackup = errors.New("invalid encrypted backup")
	ErrTruncatedBackup        = errors.New("encrypted backup is truncated")
)

// ParseEncryptionKey accepts a 32-byte key encoded as standard/raw Base64 or
// as 64 hexadecimal characters. Human passwords are intentionally rejected:
// unattended backups must use a high-entropy key generated by a CSPRNG.
func ParseEncryptionKey(value string) ([]byte, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil, fmt.Errorf("backup encryption key is empty")
	}

	encodings := []*base64.Encoding{
		base64.StdEncoding,
		base64.RawStdEncoding,
		base64.URLEncoding,
		base64.RawURLEncoding,
	}
	for _, encoding := range encodings {
		decoded, err := encoding.DecodeString(value)
		if err == nil && len(decoded) == encryptionKeySize {
			return append([]byte(nil), decoded...), nil
		}
	}
	if decoded, err := hex.DecodeString(value); err == nil && len(decoded) == encryptionKeySize {
		return decoded, nil
	}

	return nil, fmt.Errorf("backup encryption key must decode to exactly 32 bytes")
}

type EncryptWriter struct {
	destination io.Writer
	aead        cipher.AEAD
	header      [headerSize]byte
	noncePrefix [8]byte
	chunkSize   int
	buffer      []byte
	counter     uint32
	closed      bool
	err         error
}

// NewEncryptWriter creates a chunk-authenticated AES-256-GCM stream. Each
// chunk has its own nonce and authentication tag, and an authenticated final
// marker prevents silent acceptance of truncated backup files.
func NewEncryptWriter(destination io.Writer, key []byte) (*EncryptWriter, error) {
	return newEncryptWriter(destination, key, defaultChunkSize)
}

func newEncryptWriter(destination io.Writer, key []byte, chunkSize int) (*EncryptWriter, error) {
	if destination == nil {
		return nil, fmt.Errorf("backup encryption destination is nil")
	}
	if len(key) != encryptionKeySize {
		return nil, fmt.Errorf("backup encryption key must be 32 bytes")
	}
	if chunkSize < minimumChunkSize || chunkSize > maximumChunkSize {
		return nil, fmt.Errorf("backup encryption chunk size is out of range")
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}

	w := &EncryptWriter{
		destination: destination,
		aead:        aead,
		chunkSize:   chunkSize,
		buffer:      make([]byte, 0, chunkSize),
	}
	copy(w.header[:len(backupMagic)], backupMagic)
	binary.BigEndian.PutUint32(w.header[len(backupMagic):len(backupMagic)+4], uint32(chunkSize))
	if _, err := io.ReadFull(rand.Reader, w.noncePrefix[:]); err != nil {
		return nil, fmt.Errorf("generate backup encryption nonce: %w", err)
	}
	copy(w.header[len(backupMagic)+4:], w.noncePrefix[:])
	if err := writeAll(destination, w.header[:]); err != nil {
		return nil, err
	}
	return w, nil
}

func (w *EncryptWriter) Write(data []byte) (int, error) {
	if w.closed {
		return 0, errors.New("write to closed backup encryption stream")
	}
	if w.err != nil {
		return 0, w.err
	}

	written := 0
	for len(data) > 0 {
		remaining := w.chunkSize - len(w.buffer)
		if remaining > len(data) {
			remaining = len(data)
		}
		w.buffer = append(w.buffer, data[:remaining]...)
		data = data[remaining:]
		written += remaining
		if len(w.buffer) == w.chunkSize {
			if err := w.flushChunk(w.buffer); err != nil {
				w.err = err
				return written, err
			}
			w.buffer = w.buffer[:0]
		}
	}
	return written, nil
}

func (w *EncryptWriter) Close() error {
	if w.closed {
		return w.err
	}
	w.closed = true
	if w.err != nil {
		return w.err
	}
	if len(w.buffer) > 0 {
		if err := w.flushChunk(w.buffer); err != nil {
			w.err = err
			return err
		}
		w.buffer = nil
	}
	if err := w.flushChunk(nil); err != nil {
		w.err = err
		return err
	}
	return nil
}

func (w *EncryptWriter) flushChunk(plaintext []byte) error {
	if w.counter == math.MaxUint32 {
		return fmt.Errorf("backup encryption stream exceeded maximum chunk count")
	}
	if len(plaintext) > w.chunkSize {
		return fmt.Errorf("backup encryption chunk is too large")
	}

	length := uint32(len(plaintext))
	nonce := makeNonce(w.noncePrefix, w.counter)
	aad := makeAAD(w.header[:], w.counter, length)
	ciphertext := w.aead.Seal(nil, nonce[:], plaintext, aad)

	var recordHeader [4]byte
	binary.BigEndian.PutUint32(recordHeader[:], length)
	if err := writeAll(w.destination, recordHeader[:]); err != nil {
		return err
	}
	if err := writeAll(w.destination, ciphertext); err != nil {
		return err
	}
	w.counter++
	return nil
}

type DecryptReader struct {
	source      io.Reader
	aead        cipher.AEAD
	header      [headerSize]byte
	noncePrefix [8]byte
	chunkSize   int
	counter     uint32
	pending     []byte
	done        bool
	err         error
}

func NewDecryptReader(source io.Reader, key []byte) (*DecryptReader, error) {
	if source == nil {
		return nil, fmt.Errorf("backup decryption source is nil")
	}
	if len(key) != encryptionKeySize {
		return nil, fmt.Errorf("backup decryption key must be 32 bytes")
	}

	r := &DecryptReader{source: source}
	if _, err := io.ReadFull(source, r.header[:]); err != nil {
		return nil, fmt.Errorf("%w: missing header", ErrTruncatedBackup)
	}
	if string(r.header[:len(backupMagic)]) != backupMagic {
		return nil, fmt.Errorf("%w: unknown format", ErrInvalidEncryptedBackup)
	}
	r.chunkSize = int(binary.BigEndian.Uint32(r.header[len(backupMagic) : len(backupMagic)+4]))
	if r.chunkSize < minimumChunkSize || r.chunkSize > maximumChunkSize {
		return nil, fmt.Errorf("%w: invalid chunk size", ErrInvalidEncryptedBackup)
	}
	copy(r.noncePrefix[:], r.header[len(backupMagic)+4:])

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	r.aead, err = cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return r, nil
}

func (r *DecryptReader) Read(destination []byte) (int, error) {
	if len(destination) == 0 {
		return 0, nil
	}
	if len(r.pending) > 0 {
		n := copy(destination, r.pending)
		r.pending = r.pending[n:]
		return n, nil
	}
	if r.err != nil {
		return 0, r.err
	}
	if r.done {
		return 0, io.EOF
	}

	plaintext, final, err := r.readChunk()
	if err != nil {
		r.err = err
		return 0, err
	}
	if final {
		r.done = true
		return 0, io.EOF
	}
	r.pending = plaintext
	return r.Read(destination)
}

func (r *DecryptReader) readChunk() ([]byte, bool, error) {
	if r.counter == math.MaxUint32 {
		return nil, false, fmt.Errorf("%w: too many chunks", ErrInvalidEncryptedBackup)
	}

	var recordHeader [4]byte
	if _, err := io.ReadFull(r.source, recordHeader[:]); err != nil {
		return nil, false, fmt.Errorf("%w: missing final marker", ErrTruncatedBackup)
	}
	length := binary.BigEndian.Uint32(recordHeader[:])
	if length > uint32(r.chunkSize) {
		return nil, false, fmt.Errorf("%w: chunk length exceeds header limit", ErrInvalidEncryptedBackup)
	}

	ciphertext := make([]byte, int(length)+r.aead.Overhead())
	if _, err := io.ReadFull(r.source, ciphertext); err != nil {
		return nil, false, fmt.Errorf("%w: incomplete encrypted chunk", ErrTruncatedBackup)
	}
	nonce := makeNonce(r.noncePrefix, r.counter)
	aad := makeAAD(r.header[:], r.counter, length)
	plaintext, err := r.aead.Open(nil, nonce[:], ciphertext, aad)
	if err != nil {
		return nil, false, fmt.Errorf("%w: authentication failed", ErrInvalidEncryptedBackup)
	}
	r.counter++

	if length != 0 {
		return plaintext, false, nil
	}
	var trailing [1]byte
	n, err := r.source.Read(trailing[:])
	if n > 0 || err == nil {
		return nil, false, fmt.Errorf("%w: trailing data after final marker", ErrInvalidEncryptedBackup)
	}
	if !errors.Is(err, io.EOF) {
		return nil, false, fmt.Errorf("%w: read final marker: %v", ErrInvalidEncryptedBackup, err)
	}
	return nil, true, nil
}

func makeNonce(prefix [8]byte, counter uint32) [12]byte {
	var nonce [12]byte
	copy(nonce[:8], prefix[:])
	binary.BigEndian.PutUint32(nonce[8:], counter)
	return nonce
}

func makeAAD(header []byte, counter uint32, length uint32) []byte {
	aad := make([]byte, len(header)+8)
	copy(aad, header)
	binary.BigEndian.PutUint32(aad[len(header):len(header)+4], counter)
	binary.BigEndian.PutUint32(aad[len(header)+4:], length)
	return aad
}

func writeAll(destination io.Writer, data []byte) error {
	for len(data) > 0 {
		n, err := destination.Write(data)
		if err != nil {
			return err
		}
		if n <= 0 {
			return io.ErrShortWrite
		}
		data = data[n:]
	}
	return nil
}
